version: 2
jobs:
  build_and_deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      BUILD_APP: build/libs/mojingo_backend_app.jar # 成果物
      HOST_NAME: 104.199.186.211 # デプロイ先のホスト名
        USER_NAME: mojingo_app  # デプロイ先のユーザー名
        APP_DIR: /opt/mojingov2/backend/ #デプロイ先のディレクトリ
        SERVICE_NAME: mojingov2-backend
    steps:
      - checkout
      # 依存関係をダウンロードしてキャシュする
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
      - run:
          name: Build and Generate JAR
          command: gradle jar
      # 設定した秘密鍵のFingerPrintを追記する
      - add_ssh_keys:
          fingerprints:
            - "d0:7e:4a:d2:97:8e:d4:43:13:67:d1:d3:7c:a8:97:8c"
      - deploy:
          name: deployment
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
            sudo apt install -y rsync
            ssh ${USER_NAME}@${HOST_NAME} "sudo systemctl stop ${APP_NAME} " # サービスを停止する
            rsync -auz ${BUILD_APP} ${USER_NAME}@${HOST_NAME}:${APP_DIR} # 成果物をデプロイする
            ssh ${USER_NAME}@${HOST_NAME} "sudo systemctl start ${APP_NAME} " # サービスを起動する
workflows:
  version: 2
  build_and_deploy: # workflow名
    jobs:
      - build_and_deploy:
          #          requires: # buildとtestが成功したら
          #            - build
          #            - test
          filters:
            branches: # masterブランチのみ実行する
              only:
                - master
